"""
В этом файле включаются настройки pytest. Здесь нужно указать примерный путь pythonpath = . чтобы пакет app находился при запуске тестов, и asyncio_mode = auto, чтобы async-фикстуры работали нормально. Если вы хотите убрать warnings, здесь же добавляется filterwarnings.
"""